/*
 * Created on 2025-07-28 ( 02:53:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 3.3.0
 */
package com.project.PCBuilder.rest.services;

import java.util.List;
import java.util.Optional;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.project.PCBuilder.persistence.entities.Cpucooler;
import com.project.PCBuilder.persistence.repositories.CpucoolerRepository;
import com.project.PCBuilder.rest.dto.CpucoolerDTO;
import com.project.PCBuilder.rest.services.commons.GenericService;

import com.project.PCBuilder.persistence.entities.Parts;
import com.project.PCBuilder.persistence.repositories.PartsRepository;

/**
 * REST service for entity "Cpucooler" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * Enhanced to handle foreign key relationships and one-to-one cascading <br>
 * 
 * @author Telosys
 *
 */
@Service
@Transactional
public class CpucoolerService extends GenericService<Cpucooler, CpucoolerDTO> {

	private static final Logger logger = LoggerFactory.getLogger(CpucoolerService.class);

	private final CpucoolerRepository repository; // injected by constructor

	private final PartsRepository partsRepository;

	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 * @param partsRepository the Parts repository to be injected
	 */
	public CpucoolerService(CpucoolerRepository repository, PartsRepository partsRepository) {
		super(Cpucooler.class, CpucoolerDTO.class);
		this.repository = repository;
		this.partsRepository = partsRepository;
	}
	
	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private Integer getEntityId(CpucoolerDTO dto) {
		return dto.getPartid();
	}

	/**
	 * Validates foreign key references before saving
	 *
	 * @param dto
	 * @throws IllegalArgumentException if any FK reference is invalid
	 */
	private void validateForeignKeyReferences(CpucoolerDTO dto) {
		// Validate Parts reference
		if (dto.getPartid() != null) {
			if (!partsRepository.existsById(dto.getPartid())) {
				throw new IllegalArgumentException("Invalid Parts reference: " + dto.getPartid());
			}
		}
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<CpucoolerDTO> findAll() {
		logger.debug("findAll()");
		Iterable<Cpucooler> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param partid 
	 * @return the entity or null if not found
	 */
	public CpucoolerDTO findById(Integer partid) {
		Integer entityId = partid;
		logger.debug("findById({})", entityId);
		Optional<Cpucooler> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist) <br>
	 * Validates foreign key references before saving
	 *
	 * @param partid 
	 * @param dto 
	 */
	public void save(Integer partid, CpucoolerDTO dto) {
		Integer entityId = partid;
		logger.debug("save({},{})", entityId, dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		// force PK in DTO (just to be sure to conform with the given PK) 
		dto.setPartid(partid);


		repository.save(dtoToEntity(dto));
	}

	/**
	 * Updates the given entity if it exists <br>
	 * Validates foreign key references before updating
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(CpucoolerDTO dto) {
		logger.debug("update({})", dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // found and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists <br>
	 * Validates foreign key references for non-null FK fields
	 *
	 * @param partid 
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(Integer partid, CpucoolerDTO dto) {
		Integer entityId = partid;
		logger.debug("partialUpdate({}, {})", entityId, dto);
		
		Optional<Cpucooler> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			Cpucooler entity = optionalEntity.get();
			
			// Update only non-null fields from DTO
			if (dto.getRpm() != null) {
				entity.setRpm(dto.getRpm());
			}
			if (dto.getNoiseLevel() != null) {
				entity.setNoiseLevel(dto.getNoiseLevel());
			}
			if (dto.getColor() != null) {
				entity.setColor(dto.getColor());
			}
			if (dto.getSize() != null) {
				entity.setSize(dto.getSize());
			}
			
			repository.save(entity);
			return true; // found and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity <br>
	 * Validates foreign key references before creating
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(CpucoolerDTO dto) {
		logger.debug("create({})", dto);
		
		// Validate foreign key references
		validateForeignKeyReferences(dto);
		
		if (repository.existsById(getEntityId(dto))) {
			return false; // already exists, not created
		} else {
			repository.save(dtoToEntity(dto));
			return true; // created
		}
	}


	/**
	 * Deletes an entity by its PK <br>
	 * Handles cascading delete for one-to-one relationships
	 *
	 * @param partid 
	 * @return true if deleted, false if not found
	 */
	
	public boolean deleteById(Integer partid) {
		Integer entityId = partid;
		logger.debug("deleteById({})", entityId);
		
		if (repository.existsById(entityId)) {
			
			repository.deleteById(entityId);
			return true; // found and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders" for foreign key relationships
	// -----------------------------------------------------------------------------------------
	
	/**
	 * Finds entities by Parts reference
	 *
	 * @param partid the Parts ID
	 * @return list of entities
	 */
	/***
	public List<CpucoolerDTO> findByParts(Integer partid) {
		logger.debug("findByParts({})", partid);
		List<Cpucooler> list = repository.findByPartID(partid);
		return entityListToDtoList(list);
	}


/***
	// Example custom finders - uncomment and modify as needed
	public List<CpucoolerDTO> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		List<Cpucooler> list = repository.findByTitleContaining(title);
		return entityListToDtoList(list);
	}

	public List<CpucoolerDTO> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		List<Cpucooler> list = repository.findByPrice(price);
		return entityListToDtoList(list);
	}
***/
}